export const events = [
  {
    title: "React Conf 2025",
    image: "/images/event1.png",
    slug: "react-conf-2025",
    location: "San Francisco, CA",
    date: "2025-05-15",
    time: "9:00 AM",
  },
  {
    title: "GitHub Universe",
    image: "/images/event2.png",
    slug: "github-universe",
    location: "Remote",
    date: "2025-11-12",
    time: "10:00 AM",
  },
  {
    title: "DevWeek Austin",
    image: "/images/event3.png",
    slug: "devweek-austin",
    location: "Austin, TX",
    date: "2025-03-10",
    time: "8:30 AM",
  },
  {
    title: "Hack the North",
    image: "/images/event4.png",
    slug: "hack-the-north",
    location: "Waterloo, Canada",
    date: "2025-09-19",
    time: "6:00 PM",
  },
  {
    title: "JSConf Budapest",
    image: "/images/event5.png",
    slug: "jsconf-budapest",
    location: "Budapest, Hungary",
    date: "2025-05-22",
    time: "9:00 AM",
  },
  {
    title: "Next.js Meetup NYC",
    image: "/images/event6.png",
    slug: "nextjs-meetup-nyc",
    location: "New York, NY",
    date: "2025-04-08",
    time: "6:30 PM",
  },
  {
    title: "AWS re:Invent",
    image: "/images/event-full.png",
    slug: "aws-reinvent",
    location: "Las Vegas, NV",
    date: "2025-12-01",
    time: "8:00 AM",
  },
] as const;
